### ISSUE TITLE
User space GPU driver equipped in Ubuntu version?

### ISSUE THREAD

**Issue by blueardour** [wincle626/Hikey970_Debian_Linux_Installation#6]
Hi, @wincle626 

Thanks for the informative project. I noticed in your page that: The latest Lebian from Lemaker has delivered userspace binary driver for G72. The binary library is /usr/lib/aarch64-linux-gnu/libmali.so

However, I checked my system, but seemed the /usr/lib/aarch64-linux-gnu/libmali.so file not exists.  My system is downloaded from latest Lebubutu from Lemaker. I wonder if the driver only is delivered in the Lebian image?  
As far as I know, there are three image available on the Lemaker website. The ASOP, the Lebubutu, and the Lebian. I didn't know whether only the last one has a GPU driver inside, or the other two also have it but in a different folder?

**Comment by wincle626** [comment]
The quick answer is, I am not sure. 

The userspace binary driver is totally depended on either ARM or the maker. I did not follow Lemaker website for a while. It seems there are five Linux version for Hikey 970 board so far which is a lot. 

This repo is quite old now. So the pre-compiled image I used might not be the latest one and I cannot recall which one I used before. So unfortunately, you can only try different version to see if the driver is provided. 

Another thing you can try is to search your system to see if the library is placed in different folder with following steps:
1. cd /
2. sudo find . -name libmali.so 
If something shows up, you will know where the library is. (ps: you can replace libmali.so by *mali*)

Good luck!

**Comment by blueardour** [comment]
Thank you. I might give a try.
